spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bookmark
    username: sa
    password:
    platform: h2
  h2:
    console:
      enabled: true
      path: /h2-console
